// Code generated by github.com/foolin/gocsv.
// source: data.csv
// DO NOT EDIT! 

package data

type Data struct {
	Id    int `csv:"id"`        //Goods Id
	Name  string `csv:"name"`   //Goods Name
	Price float64 `csv:"price"` //价格
}
