// Code generated by github.com/foolin/gocsv.
// source: data_under.csv
// DO NOT EDIT! 

package data

type DataUnder struct {
	Id int `csv:"id"` //Goods Id
	GoodsName string `csv:"goods_name"` //Goods Name
	Price float32 `csv:"price"` //价格
}
